- hosts: "{{ server | default('hadoop_pseudo') }}"
  tasks:
    - name: start_namenode
      shell: /usr/sbin/service hadoop-hdfs-namenode start

    - name: wait_for_namenode_service_port
      wait_for: host={{ ansible_hostname }} port=50070

    - name: start_secondarynamenode
      shell: /usr/sbin/service hadoop-hdfs-secondarynamenode start

    - name: wait_for_secondarynamenode_web_service_port_started
      wait_for: host={{ ansible_hostname }} port=50090 state=started

    - name: start_datnode
      shell: /usr/sbin/service hadoop-hdfs-datanode start

    - name: wait_for_datanode_service_port
      wait_for: host={{ ansible_hostname }} port=50020
