- hosts: "{{ server | default('hadoop_pseudo') }}"
  tasks:
    - name: stop_resourcemanager
      shell: /usr/sbin/service hadoop-yarn-resourcemanager  stop

    - name: wait_for_resourcemanager_web_service_port_stopped
      wait_for: host={{ ansible_host }} port=8088 state=stopped

    - name: stop_nodemanager
      shell: /usr/sbin/service hadoop-yarn-nodemanager  stop

    - name: wait_for_nodemanager_service_port_stopped
      wait_for: host={{ ansible_host }}  port=8040 state=stopped
