- include: stop_zookeeper.yml

- include: start_zookeeper.yml

- hosts: hadoop_namenode_primary
  become_user: hdfs
  become: true
  tasks:
    - name: init_zkfc
      shell: yes Y | hdfs zkfc -formatZK

# vim: et ts=2 sw=2
