- hosts: hadoop_zookeeperserver
  gather_facts: no
  tasks:
    - name: stop_daemons
      shell: /usr/sbin/service zookeeper-server stop
    - name: wait_for_zookeeper_service_port_close
      wait_for: host={{ ansible_host }} port=2181 state=stopped
