- hosts: "{{ server | default(groups.hadoop_namenode) }}"
  tasks:
    - name: stop_zkfc
      shell: /usr/sbin/service hadoop-hdfs-zkfc stop

    - name: wait_for_namenode_service_port
      wait_for: host={{ ansible_host }} port=8019 state=stopped

- hosts: "{{ server | default(groups.hadoop_namenode) }}"
  tasks:
    - name: stop_namenode
      shell: /usr/sbin/service hadoop-hdfs-namenode stop

    - name: wait_for_namenode_service_port
      wait_for: host={{ ansible_host }} port=50070 state=stopped

- hosts: "{{ server | default(groups.hadoop_journalnode) }}"
  tasks:
    - name: stop_journalnode
      shell: /usr/sbin/service hadoop-hdfs-journalnode stop

    - name: wait_for_journalnode_service_port
      wait_for: host={{ ansible_host }} port=8480 state=stopped

- hosts: "{{ server | default(groups.hadoop_slave) }}"
  tasks:
    - name: stop_datnode
      shell: /usr/sbin/service hadoop-hdfs-datanode stop

    - name: wait_for_datanode_service_port
      wait_for: host={{ ansible_host }} port=50020 state=stopped
