---
# tasks file for roles/openjdk
- block:

  - name: install_openjdk
    yum: name=java-1.8.0-openjdk-devel state=installed
  - name: configure_JAVA_HOME
    template:
      src: java_home.sh.j2
      dest: /etc/profile.d/java_home.sh

  tags:
    - openjdk
