- hosts: '{{server | default("hadoop_client") }}'
  become: True
  become_user: hdfs
  tasks:
    - name: remove_spark_log_dir
      shell: hdfs dfs -rm -r /var/log/spark/apps 
    - name: mkdir_spark_log_dir
      shell: hdfs dfs -mkdir -p /var/log/spark/apps 
    - name: chown_spark_log_dir
      shell: hdfs dfs -chown spark /var/log/spark/apps 
    - name: chmod_spark_log_dir
      shell: hdfs dfs -chmod a+w /var/log/spark/apps 
