- hosts: '{{server | default("hadoop_other") }}'
  become: yes
  become_user: hdfs
  tasks:
    - name: stop_spark_history_server
      shell: bash /usr/local/spark/default/sbin/stop-history-server.sh
      register: shell_result
      failed_when: shell_result.rc not in [0, 1] 
      changed_when: shell_result.rc == 0
    - name: wait_for_spark_history_server_web_service_port
      wait_for: host={{ ansible_host }} port=18080 state=stopped
