---
# tasks file for roles/hadoop_base
- block:

  - name: add_bigtop.repo
    yum_repository:
      name: Bigtop
      file: bigtop
      description: Bigtop
      enabled: yes
      gpgcheck: yes
      gpgkey: https://dist.apache.org/repos/dist/release/bigtop/KEYS
      baseurl: http://repos.bigtop.apache.org/releases/1.4.0/centos/7/$basearch

  - name: install_hadoop
    yum:
      name: hadoop
      state: installed

  tags:
    - hadoop_base
