---
# tasks file for roles/hadoop_base
- block:

  - name: add_bigtop.repo
    yum_repository:
      name: Bigtop
      file: bigtop
      description: Bigtop
      enabled: yes
      gpgcheck: yes
      gpgkey: https://dist.apache.org/repos/dist/release/bigtop/KEYS
      baseurl: http://repos.bigtop.apache.org/releases/1.4.0/centos/7/$basearch

  - name: install_hadoop
    yum:
      name: ["hadoop", "hadoop-hdfs", "hadoop-yarn", "hadoop-mapreduce", "zookeeper"]
      state: installed

  - name: configure_hadoop-env.sh
    template:
      src: hadoop-env.sh.j2
      dest: /etc/hadoop/conf/hadoop-env.sh

  - name: configure_core-site.xml
    template:
      src: core-site.xml.j2
      dest: /etc/hadoop/conf/core-site.xml

  - name: configure_hdfs-site.xml
    template:
      src: hdfs-site.xml.j2
      dest: /etc/hadoop/conf/hdfs-site.xml

  - name: configure_yarn-site.xml
    template:
      src: yarn-site.xml.j2
      dest: /etc/hadoop/conf/yarn-site.xml

  - name: configure_hadoop-metrics2.property
    template:
      src: hadoop-metrics2.properties.j2
      dest: /etc/hadoop/conf/hadoop-metrics2.properties
    when: hadoop_base_ganglia == True

  tags:
    - hadoop_base
