---
# tasks file for roles/hadoop_nn
- block:
  - name: install_hadoop_namenode
    yum:
      name: ["hadoop-hdfs-namenode", "hadoop-hdfs-zkfc"]
      state: installed

  - name: disable_namenode
    service: 
      name: "{{item}}"
      enabled: no
    with_items:
      - hadoop-hdfs-zkfc
      - hadoop-hdfs-namenode

  tags:
    - hadoop_nn
