- hosts: "{{ server | default(groups.hadoop_resourcemanager) }}"
  tasks:
    - name: start_resourcemanager
      shell: /usr/sbin/service hadoop-yarn-resourcemanager start

    - name: wait_for_resourcemanager_web_service_port
      wait_for: host={{ ansible_host }}  port=8088

- hosts: "{{ server | default(groups.hadoop_slave) }}"
  tasks:
    - name: start_nodemanager
      shell: /usr/sbin/service hadoop-yarn-nodemanager start

    - name: wait_for_nodemanager_service_port
      wait_for: host={{ ansible_host }} port=8040

