- hosts: "{{ server | default(groups.hadoop_client[0]) }}"
  become: True
  become_user: hdfs
  tasks:
    - name: make_warehouse_dir
      shell: hdfs dfs -mkdir -p /user/hive/warehouse

    - name: chmod_warehouse_dir
      shell: hdfs dfs -chmod 775 /user/hive

    - name: chown_warehouse_dir
      shell: hdfs dfs -chown -R hive:hive /user/hive
