---
# tasks file for roles/tmux

- block:

  - name: install_tmux
    yum:
      name: tmux 
      state: installed
  
  - name: deploy_tmux.conf
    template: 
      src: tmux.conf 
      dest: /etc/tmux.conf
      mode: 644

  tags: tmux
