---
# tasks file for roles/pyenv

- block:

  - name: install_pyenv
    shell: curl https://pyenv.run | bash
  - name: configure_PATH
    lineinfile:
      line: export PATH="$HOME/.pyenv/bin:$PATH"
      path: "{{ ansible_env.HOME }}/.bashrc"
  - name: configure_pyenv_init
    lineinfile:
      line: eval "$(pyenv init -)"
      path: "{{ ansible_env.HOME }}/.bashrc"
  - name: configure_virtualenv_init
    lineinfile:
      line: eval "$(pyenv virtualenv-init -)"
      path: "{{ ansible_env.HOME }}/.bashrc"

  tags:
    - pyenv
