- block:

  - name: install_screen
    yum: 
      name: screen
      state: installed

  - name: copy_screenrc
    template: 
      src: screenrc.j2
      dest: /etc/screenrc
      mode: 644

  tags:
    - screen
