- hosts: "{{ server | default('hadoop_all') }}"
  tasks:
    - name: start_gmond
      shell: /usr/sbin/service gmond start

- hosts: "{{ server | default('hadoop_other') }}"
  tasks:
    - name: start_httpd
      shell: /usr/sbin/service httpd start
    - name: start_gmetad
      shell: /usr/sbin/service gmetad start
