- hosts: "{{ server | default('hadoop_all') }}"
  tasks:
    - name: stop_gmond
      shell: /usr/sbin/service gmond stop

- hosts: "{{ server | default('hadoop_other') }}"
  tasks:
    - name: stop_httpd
      shell: /usr/sbin/service httpd stop
    - name: stop_gmetad
      shell: /usr/sbin/service gmetad stop
