- hosts: "{{ server | default('hadoop_all') }}"
  roles:
    - common
    - epel
    - openjdk
    - hadoop_base

- hosts: "{{ server | default('hadoop_zookeeperserver') }}"
  roles:
    - hadoop_zk

- hosts: "{{ server | default('hadoop_journalnode') }}"
  roles:
    - hadoop_jn

- hosts: "{{ server | default('hadoop_namenode') }}"
  roles:
    - hadoop_nn

- hosts: "{{ server | default('hadoop_resourcemanager') }}"
  roles:
    - hadoop_rm

- hosts: "{{ server | default('hadoop_slave') }}"
  roles:
    - hadoop_dn
    - hadoop_nm
